Fix

diff --git a/.github/workflows/orchestrator.yml b/.github/workflows/orchestrator.yml
--- a/.github/workflows/orchestrator.yml
+++ b/.github/workflows/orchestrator.yml
@@ -22,33 +22,33 @@ jobs:
         run: |
           gh workflow run collector.yml --repo $COLLECTOR_REPO
 
-       - name: Wait for Collector Completion
+      - name: Wait for Collector Completion
         run: |
-            echo "Waiting for Collector pipeline to complete..."
-            sleep 5
-        
-            while true; do
-                # Verifica el estado del pipeline
-                running=$(gh run list --repo $COLLECTOR_REPO --status in_progress --json databaseId | jq length)
-                failed=$(gh run list --repo $COLLECTOR_REPO --status failure --json databaseId | jq length)
-        
-                # Si no hay ejecuciones activas
-                if [[ "$running" -eq 0 ]]; then
-                    if [[ "$failed" -gt 0 ]]; then
-                        echo "Collector pipeline failed. Exiting..."
-                        exit 1
-                    fi
-        
-                    echo "Collector pipeline completed successfully."
-                    break
-                fi
-        
-                echo "Waiting for Collector pipeline to complete..."
-                sleep 15
-            done
+          echo "Waiting for Collector pipeline to complete..."
+          sleep 5
+      
+          while true; do
+              # Verifica el estado del pipeline
+              running=$(gh run list --repo $COLLECTOR_REPO --status in_progress --json databaseId | jq length)
+              failed=$(gh run list --repo $COLLECTOR_REPO --status failure --json databaseId | jq length)
+      
+              # Si no hay ejecuciones activas
+              if [[ "$running" -eq 0 ]]; then
+                  if [[ "$failed" -gt 0 ]]; then
+                      echo "Collector pipeline failed. Exiting..."
+                      exit 1
+                  fi
+      
+                  echo "Collector pipeline completed successfully."
+                  break
+              fi
+      
+              echo "Waiting for Collector pipeline to complete..."
+              sleep 15
+          done
         
 
-       - name: Get Collector Outputs
+      - name: Get Collector Outputs
         run: |
           # Obtener el run-id
           run_id=$(gh run list --repo $COLLECTOR_REPO --status completed --json databaseId --jq '.[0].databaseId')
